### ISSUE TITLE
Mapping Custom OSC Messages

### ISSUE THREAD

**Issue by chrisspiegl** [Andymann/ofxOscMidi#1]
Hi Andy, interesting project you have here. Very easy to use and a minimal setup.

I came across this project because I was looking for an open source program that can map MIDI to OSC. Now your project already got me half way.

The idea is to use a MIDI control surface to control the ATEM Mini and there is a program that can do this via OSC but the MIDI surface needs to be mapped to specific OSC commands (https://github.com/SteffeyDev/atemOSC).

Are you looking to implement a way to map MIDI notes to OSC commands?

Becuase right now, it just maps MIDI to a pre defined structure as far as I can tell?

Thanks for even making this available. Looking forward to hearing from you in the future.

Chris

**Comment by andymann** [comment]
Hey Chris,I like your Idea. 

Already had this in my mind for some time but I was waiting for some inspiration on how to best implement this.Think I Just had an idea (because things like this often happen to me as soon as someone contacts me :) ).Might take me a few days.

**Comment by chrisspiegl** [comment]
Thanks for your reply. Just an FYI from my side. I was thinking of using this together with atemOSC but now I found out that I can just code my own solution with Node.JS and a package which provides a direct connection to the ATEM Mini via network control.

So I will probably not be using your program for my purposes. But I am sure others may still find it interesting.

Random question: what did you build this program for? Where are you receiving/sending these messages from and to?

**Comment by andymann** [comment]
Thx for the feedback. Glad you already found a solution. I like your idea anyways and will have a look at an implementation either way.
As far as I remember I simply thought that it might be a cool thing to build.
