### ISSUE TITLE
Double digit channel numbers

### ISSUE THREAD

**Issue by laurenschroeder** [Andymann/ofxOscMidi#2]
Hey, love this app, seems to be the best one I've found for this purpose.

I noticed that I can only configure MIDI channels 0-9 when sending control change messages. Seems like double digits aren't allowed. Would be awesome to have this functionality included out of the box.

**Comment by andymann** [comment]
Hey Lauren, thx for the feedback. I'll give e it a look but it might take me a few days (weeks). 
Just out of curiosity: What are you using the software for?

**Comment by andymann** [comment]
Finally fixed. Sorry it took so long
